use dairy;

-- Total revenue generated by each product 
select product_name,sum(approx_total_revenue) as Total_revenue
from dairy_sales
group by product_name;

--  Give Brand with the highest total revenue 
select brand,sum(approx_total_revenue) as Total_revenue
from dairy_sales
group by brand
order by Total_revenue DESC
limit 1;

-- Give Monthly revenue trend across all products 
select month(date) as month,sum(approx_total_revenue) as Total_revenue
from dairy_sales
group by month(date)
order by month(date);

-- : Products below the minimum stock threshold
 select product_name,quantity,minimum_stock_threshold
 from dairy_sales
 where quantity < minimum_stock_threshold;
 
 -- Total reorder quantity required per product 
 select product_name, sum(reorder_quantity) as total_reorder_quantity
 from dairy_sales
 group by product_name;
 
 -- Which sales channel generates the most revenue
 select sales_channel,sum(approx_total_revenue) as total_revenue
 from dairy_sales
 group by sales_channel 
 order by total_revenue DESC
 limit 1;
 
 -- Top 5 customer locations by purchase volume
 select customer_location,sum(quantity_sold) as total_purchase_volume
from dairy_sales
group by customer_location
order by total_purchase_volume DESC
limit 5;

-- Average selling price per product
select product_name, avg(price_per_unit_sold) as Average_selling_price
from dairy_sales
group by product_name;

-- Compare selling price with listed price
select product_name,price_per_unit,price_per_unit_sold,
(price_per_unit_sold - price_per_unit) as price_difference
from dairy_sales;

-- Products with less than 10 days shelf life remaining
select product_name,date,expiration_date,
datediff(expiration_date,date) as days_remaining
from dairy_sales
where datediff(expiration_date,date) between 0 and 9;

-- Average shelf life by product category
select product_name,avg(shelf_life_days) as Average_shelf_life_days
from dairy_sales
group by product_name;

-- Average number of cows per farm size category
select farm_size,avg(number_of_cows) as Average_cows
from dairy_sales
group by farm_size;

-- Location with the largest total land area
select location,sum(total_land_area) as total_land_area
from dairy_sales
group by location
order by total_land_area DESC
limit 1;

-- Top 3 locations by average production quantity
select location,avg(quantity) as average_production_quantity
from dairy_sales
group by location
order by average_production_quantity DESC
limit 3;

-- Calculate profit for each product
select product_name,
sum(approx_total_revenue)-sum(price_per_unit*quantity_sold) as profit
from dairy_sales
group by product_name;

-- Most profitable brand overall
select brand,
sum(approx_total_revenue)-sum(price_per_unit*quantity_sold) as profit
from dairy_sales
group by brand
order by profit DESC
limit 1;

-- Yearly revenue growth
select year(date) as Year,
sum(approx_total_revenue) as total_revenue
from dairy_sales
group by year(date)
order by Year;

-- Best-selling product each year
select year, product_name,total_quantity_sold
from ( 
select
year(date) as year,
product_name,
sum(quantity_sold) as total_quantity_sold,
rank() over (
partition by year(date)
order by sum(quantity_sold) desc) as rnk
from dairy_sales
group by year(date),product_name
)as ranked_products 
where rnk = 1
order by year;

-- Products that need immediate restock
select product_name, quantity_in_stock,minimum_stock_threshold
from dairy_sales
where quantity_in_stock < minimum_stock_threshold;

-- Identify expired products still in stock
select product_name,expiration_date,quantity_in_stock
from dairy_sales 
where expiration_date < date
and quantity_in_stock > 0;

-- Average shelf life per brand
select brand,avg(shelf_life_days) as average_shelf_life
from dairy_sales
group by brand;
